from turtle import *
import time 

setup(1000, 1000)
bgcolor("black")
speed(0)
hideturtle()
pensize(2)
pencolor("red")
tracer(0,0)
for i in range(1,75):
    penup()
    goto(0,0)
    setheading(i*4)
    forward(8)
    pendown()
    forward(1*5)
    penup()
    goto(0,0)
    setheading(i*4+180)
    forward(8)
    pendown()
    forward(1*5)
    update()
    time.sleep(0.02)
done()